rules = rule rules | '';
rule = letters '=' alternatives ';';
alternatives = production productions | '';
productions = '|' production productions | '';
production = word production | '';
word = letters | string;
string = "'" letters "'";
letters = letter letters | '';
letter = 'a' | 'b' | 'c' | 'd' | 'e' | 'f' | 'g' | 'h' | 'i' | 'j' |
		 'k' | 'l' | 'm' | 'n' | 'o' | 'p' | 'q' | 'r' | 's' | 't' |
		 'u' | 'v' | 'w' | 'x' | 'y' | 'z';  